version: '3.8'
services:
  app:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ticketingSystemDb
      - SPRING_DATASOURCE_USERNAME=ticketuser
      - SPRING_DATASOURCE_PASSWORD=2580

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2580
      MYSQL_DATABASE: ticketingSystemDb
      MYSQL_USER: ticketuser
      MYSQL_PASSWORD: 2580
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
